### ISSUE TITLE
missing toy.decoy.sam file

### ISSUE THREAD

**Issue by chenli-bioinfo** [progistar/pXg#1]
Dear authors,

I was trying to run the post-processing steps and found that the toy.decoy.sam file is missing. Could you provide it or indicate how this file can be generated?

Thank you very much.

**Comment by progistar** [comment]
Hi,

I updated the tutorial files. So please check the updated version.
I hope you can easily find several resources including a runnable bash file and toy data in 'tutorial" folder.

Thank you for your interest in pXg!

**Comment by chenli-bioinfo** [comment]
Thank you very much.

May I ask how the decoy file was generated? Which tool can I use?

**Comment by progistar** [comment]
I think you meant "toy.decoy.psm" (because there is no mention about toy.decoy.sam file in the tutorial).
Once you run the post_process.py in the tutorial folder, you can get toy.decoy.psm generated by Percolator.

**Comment by chenli-bioinfo** [comment]
Sorry. Yes, I meant toy.decoy.psm.

It seems that I can't still find the file. I downloaded the pXg v2.2.1 release but the file seems not there.

**Comment by progistar** [comment]
Yes, you should download toy dataset from tutorial folder (toy_datasets.zip).
And then, run exampleRunner.sh after adjusting arguments such as file paths.
Once you get a result of pXg, you can run post_process.py.

**Comment by chenli-bioinfo** [comment]
I downloaded the current release: pXg-2.2.1-2024-02-07 and the toy dataset folder doesn't have the decoy file. 

I also went to the project's main page and downloaded and unzipped toy_dataset.zip but still can't find the file.

**Comment by progistar** [comment]
Okay.. could you let me know your e-mail address please? I will send you some tutorial video.

**Comment by chenli-bioinfo** [comment]
Sure Thanks

chen.li0810@gmail.com

**Comment by progistar** [comment]
I sent the video from my e-mail address: progistar@naver.com. I hope it works for you.
